name: movie_app
description: "A Flutter project for managing and viewing movies with a clean architecture."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  go_router: ^14.3.0
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  lottie: ^2.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  cached_network_image: ^3.4.0
  get_it: ^7.2.0
  flutter_dotenv: ^5.1.0
  intl: ^0.17.0
  sqflite: ^2.2.0
  path_provider: ^2.0.9
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^2.27.1
  shared_preferences: 2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/movie.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/lotties/
    - assets/images/
    - assets/icons/
    - assets/.env
    
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 700
